categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - '🤖 dependencies'

exclude-labels:
  - apparently external cause
  - chore
  - devops admin
  - duplicate
  - invalid
  - later
  - overcome by events
  - spike
  - wontfix
  - do not log
  - question
  - QA

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |

  # New Features

  $CHANGES

  # Usage

  More info can be found in the [installation instructions](https://docs.epinio.io/installation/installation.html).

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'dependencies'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
  default: patch
